### ISSUE TITLE
my review link is broken

### ISSUE THREAD

**Issue by mastercyb** [sgmenda/cfh#1]
i am crazy curious on your conclusion about cfh idea ...

**Comment by initsecret** [comment]
Thanks for the heads up. Unfortunately, I cannot find the file now but IIRC it was just my notes on the paper, as I tried to understand it.

I haven't thought more about the fuzzing hashing problem since I wrote this post in about Jan 2021. If you are interested in this area, a good place to get started might be the [Kulshrestha and Mayer paper](https://www.usenix.org/conference/usenixsecurity21/presentation/kulshrestha) and the [papers that cite it](https://scholar.google.com/scholar?cites=10729046934454313027).
